version: '3.8'

services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser:s6
    container_name: filebrowser
    hostname: filebrowser
    ports:
      - 8080:80
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /:/srv
      - /ctnr/data/filebrowser:/database
      - /ctnr/data/filebrowser:/config
    restart: always
