# Dim - Self-hosted media manager
# https://github.com/Dusk-Labs/dim
#
# Port: 8089 -> 8000

services:
  dim:
    image: ghcr.io/dusk-labs/dim:dev
    container_name: dim
    hostname: dim
    ports:
      - 8089:8000
    volumes:
      - /root/container/dim/data:/opt/dim/config
      - /root/drive:/media:ro
    restart: always
