# Komga - Comics and manga server
# https://github.com/gotson/komga
#
# Port: 8092 -> 25600

services:
  komga:
    image: gotson/komga
    container_name: komga
    hostname: komga
    user: "0:0"
    ports:
      - 8092:25600
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - type: bind
        source: /root/container/Stacks/komga/data
        target: /config
      - type: bind
        source: /mnt/drive/books
        target: /data
    restart: always
