# Kavita - Digital library for eBooks, comics, and manga
# https://github.com/Kareadita/Kavita
#
# Port: 8093 -> 5000

services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    hostname: kavita
    ports:
      - 8093:5000
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /root/container/Stacks/kavita/data:/config
      - /mnt/drive/books:/data
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true
