services:
  dim:
    image: ghcr.io/dusk-labs/dim:dev
    container_name: dim
    hostname: dim
    restart: always
    ports:
    - "8089:8000"
    volumes:
    - /root/container/dim/data:/opt/dim/config
    - /root/drive:/media:ro
