version: '3.8'
services:
  app:
    container_name: filestash
    image: machines/filestash
    hostname: filestash
    restart: always
    environment:
    - APPLICATION_URL=
    - GDRIVE_CLIENT_ID=<gdrive_client>
    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    - DROPBOX_CLIENT_ID=<dropbox_key>
    - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "8090:8334"
    volumes:
    - filestash:/app/data/state/

  onlyoffice:
    container_name: filestash_oods
    hostname: filestash_oods
    image: onlyoffice/documentserver:7.1
    restart: always

volumes:
  filestash: {}
