# Filestash - Web file manager with cloud integrations
# https://github.com/mickael-kerjean/filestash
#
# Port: 8090 -> 8334
# Supports: FTP, SFTP, S3, Google Drive, Dropbox, etc.

services:
  app:
    image: docker.io/machines/filestash
    container_name: filestash
    hostname: filestash
    ports:
      - 8090:8334
    environment:
      - APPLICATION_URL=
      - GDRIVE_CLIENT_ID=
      - GDRIVE_CLIENT_SECRET=
    volumes:
      - filestash:/app/data/state/
    restart: always

volumes:
  filestash:
