services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8087:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 'admin'
    volumes:
      - /root/container/pihole/config:/etc/pihole
      - /root/container/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true
