# Prowlarr - Indexer manager for *arr apps
# https://github.com/Prowlarr/Prowlarr
#
# Port: 8087 -> 9696

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    ports:
      - 8087:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /ctnr/data/prowlarr:/config
    restart: always
