version: "3.8"
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs-server
    restart: always
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /mnt:/data
    ports:
      - 2049:2049
