log:
  level: TRACE
  filePath: "/root/logs/traefik.log"
  format: json

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    network: traefik
  file:
    filename: /etc/traefik/traefik-dynamic.yaml
