http:
  routers:
    TraefikApi:
      rule: "Host(`trfk.mars.am`) && PathPrefix(`/api/`)"
      service: api@internal
    TraefikDashboard:
      rule: "Host(`trfk.mars.am`)"
      service: dashboard@internal
    Portainer:
      rule: "Host(`ptnr.mars.am`)"
      service: portainer
    PortainerHttps:
      rule: "Host(`ptnr.mars.am`)"
      service: portainer
      tls: {}
      middlewares:
        - redirect-to-http
    Filebrowser:
      rule: "Host(`file.mars.am`)"
      service: filebrowser
    Qbittorrent:
      rule: "Host(`qbit.mars.am`)"
      service: qbittorrent
    Jellyfin:
      rule: "Host(`jelly.mars.am`)"
      service: jellyfin
    Pyload:
      rule: "Host(`pyload.mars.am`)"
      service: pyload
    Filezilla:
      rule: "Host(`filezilla.mars.am`)"
      service: filezilla

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    filebrowser:
      loadBalancer:
        servers:
          - url: "http://filebrowser:80"
    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://qbittorrent:8083"
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://jellyfin:8096"
    pyload:
      loadBalancer:
        servers:
          - url: "http://pyload-ng:8000"
    filezilla:
      loadBalancer:
        servers:
          - url: "http://filezilla:5800"

  middlewares:
    redirect-to-http:
      redirectScheme:
        scheme: "http"
