apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-cleaner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-cleaner
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "delete"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-cleaner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-cleaner
subjects:
  - kind: ServiceAccount
    name: event-cleaner
    namespace: kube-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: event-cleaner
  namespace: kube-system
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: event-cleaner
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - kubectl
                - delete
                - events
                - --all
                - --all-namespaces
                - --ignore-not-found
                - --timeout=7200s
