- Infrastructure:
    - Bare Metal:
        - Proxmox:
            href: https://pve.red:8006/
            description: pve.red
            icon: proxmox.png
            widget:
                type: proxmox
                url: https://pve.red:8006/
                username:
                password:
                node: red
        - Debian:
            href:
            description: "dve.red"
            icon: debian-linux.png
            widget:
                type: portainer
                url: https://ctnr.pve.red:443
                env: 4
                key:
    - Networking:
        - Router:
            href: http://192.168.0.1/admin/index.html#/home
            description: dlinkrouter.local
            icon: router.png

- Services:
    - DNS:
        - Adgaurd:
            href: http://dns-02.pve.red/
            description: dns-02.pve.red
            icon: adguard-home.png
            widget:
                type: adguard
                url:  http://dns-02.pve.red
                username:
                password:
        - Pihole:
            href: http://dns-01.pve.red/admin/
            description: dns-01.pve.red
            icon: pi-hole.png
            widget:
                type: pihole
                url: http://dns-01.pve.red
                version: 6
                key:
    - Development:
        - Codeserver:
            href: http://codeserver.pve.red/?folder=/root/homelab
            description: codeserver.pve.red
            icon: code-server.png

- ctnr.pve.red:
    - Browsers:
        - Firefox:
            href: https://ctnr.pve.red:8081/
            description: ctnr.pve.red:8081
            icon: firefox.png
        - Librewolf:
            href: http://ctnr.pve.red:8082/
            description: ctnr.pve.red:8082
            icon: librewolf.png
    - Management:
        - Portainer:
            href: https://ctnr.pve.red/
            description: ctnr.pve.red:443
            icon: portainer.png
        - File Browser:
            href: http://ctnr.pve.red:8080
            description: ctnr.pve.red:8080
            icon: filebrowser.png
    - Chat:
        - Webcord:
            href: http://ctnr.pve.red:8083/
            description: ctnr.pve.red:8083
            icon: discord.png

- dev.red:
    - Management:
        - File Browser:
            href: http://dve.red:8082/login?redirect=/files/
            description: dve.red:8082
            icon: filebrowser.png
    - Media:
        - Jellyfin:
            href: http://dve.red:8080/
            description: dve.red:8080
            icon: jellyfin.png
    - Internet:
        - Firefox:
            href: https://dve.red:8083/
            description: dve.red:8083
            icon: firefox.png
        - Qbittorrent:
            href: http://dve.red:8081/
            description: dve.red:8081
            icon: qbittorrent.png
    - Data Transfer:
        - NFS Server:
            href:
            description: "Host: dve.red, Port: 2049, Share: /"
            icon: webkit.png
        - FTP Server:
            href:
            description: "Host: dve.red, Port: 8095/8096"
            icon: webkit.png
