- Infrastructure:
    - Bare Metal:
        - Proxmox:
            href: https://pve.red:8006/
            description: pve.red
            icon: proxmox.png
        - Proxmox:
            href: https://dve.red:8006/
            description: dve.red
            icon: proxmox.png
    - Networking:
        - Router:
            href: http://192.168.0.1/admin/index.html#/home
            description: dlinkrouter.local
            icon: router.png

- Services:
    - DNS:
        - Adgaurd:
            href: http://dns-02.pve.red/admin/
            description: dns-02.pve.red
            icon: pi-hole.png
        - Pihole:
            href: http://dns-01.pve.red/admin/
            description: dns-01.pve.red
            icon: pi-hole.png
    - Development:
        - Codeserver:
            href: http://codeserver.pve.red/?folder=/root/homelab
            description: codeserver.pve.red
            icon: code-server.png
    - Home Media:
        - Immich:
            href: http://immich.pve.red
            description: immich.pve.red
            icon: immich.png
- ctnr.pve.red:
    - Management:
        - Portainer:
            href: https://ctnr.pve.red/
            description: ctnr.pve.red:443
            icon: portainer.png
        - File Browser:
            href: http://ctnr.pve.red:8080
            description: ctnr.pve.red:8080
            icon: filebrowser.png
    - Browsers:
        - Firefox:
            href: https://ctnr.pve.red:8081/
            description: ctnr.pve.red:8081
            icon: firefox.png

- ctnr.dve.red:
    - Management:
        - File Browser:
            href: http://ctnr.dve.red:8080/login?redirect=/files/
            description: ctnr.dve.red:8080
            icon: filebrowser.png
    - Media:
        - Jellyfin:
            href: http://ctnr.dve.red:8081/
            description: ctnr.dve.red:8081
            icon: jellyfin.png
    - Internet:
        - Firefox:
            href: https://ctnr.dve.red:8082/
            description: ctnr.dve.red:8082
            icon: firefox.png
        - Qbittorrent:
            href: http://ctnr.dve.red:8083/
            description: ctnr.dve.red:8083
            icon: qbittorrent.png
    - Data Transfer:
        - FTP Server:
            href:
            description: "Host: ctnr.dve.red, Port: 8084/8085"
            icon: webkit.png
        - NFS Server:
            href:
            description: "Host: ctnr.dve.red, Port: 2049, Share: /"
            icon: webkit.png
        - Filezilla:
            href: http://ctnr.dve.red:8086/
            description: ctnr.dve.red:8086
            icon: filezilla.png
