version: "3.8"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /ctnr/data/sonarr:/config
      - /mnt/tv:/tv
      - /mnt/downloads:/downloads
    ports:
      - 8086:8989
    restart: always
