apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bootdisk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-noos
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-noos
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 512Mi
        devices:
          disks:
            - name: bootdisk
              disk:
                bus: virtio
      volumes:
        - name: bootdisk
          persistentVolumeClaim:
            claimName: bootdisk-pvc
