# Jellyfin - Media streaming server
# https://jellyfin.org/
#
# Port: 8096
# Hardware acceleration: /dev/dri passed through

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /ctnr/data/jellyfin:/config
      - /mnt:/data
    devices:
      - /dev/dri:/dev/dri
    restart: always
