version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /ctnr/data/jellyfin:/config
      - /mnt:/data
    ports:
      - 8096:8096
    restart: always
    devices:
      - /dev/dri:/dev/dri
    hostname: jellyfin
