# Portainer - Container management UI
# https://portainer.io/
#
# Port: 8081 -> 9000
# Configured for Podman socket

services:
  portainer:
    image: docker.io/portainer/portainer-ee:2.21.3
    container_name: portainer
    hostname: portainer
    command: --http-enabled
    ports:
      - 8081:9000
    volumes:
      - /var/run/podman/podman.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik
    restart: always

volumes:
  portainer_data:

networks:
  traefik:
    external: true
