# Font
font-family = JetBrains Mono
font-style = Bold
font-size = 14
font-feature = calt
font-feature = liga

# Theme (Nord)
background = #2e3440
foreground = #d8dee9
selection-foreground = #eceff4
selection-background = #4c566a
palette = 0=#3b4252
palette = 1=#bf616a
palette = 2=#a3be8c
palette = 3=#ebcb8b
palette = 4=#81a1c1
palette = 5=#b48ead
palette = 6=#88c0d0
palette = 7=#e5e9f0
palette = 8=#4c566a
palette = 9=#bf616a
palette = 10=#a3be8c
palette = 11=#ebcb8b
palette = 12=#81a1c1
palette = 13=#b48ead
palette = 14=#8fbcbb
palette = 15=#eceff4

# Cursor
cursor-style = block
cursor-style-blink = false
cursor-color = #88c0d0

# Window
title = Term
scrollbar = never
window-padding-x = 16
window-padding-y = 16
window-width = 120
window-height = 30

# Terminal
term = xterm-256color

# Shell
command = /bin/zsh
shell-integration-features = no-cursor
