apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: homepage
  name: homepage
  namespace: kube-system
data:
  bookmarks.yaml: |
    - Search Engine:
        - Duck Duck Go:
            - abbr: DDG
              href: https://duck.com/
              icon: duckduckgo.png
        - Brave:
            - abbr: BS
              href: https://search.brave.com/
              icon: brave.png
        - Google:
            - abbr: GGL
              href: https://google.com/
              icon: google.png

    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
              icon: github.png

    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/
              icon: reddit.png
        - fosstodon:
            - addr: FD
              href: https://fosstodon.org/explore
              icon: mastodon.png

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
              icon: youtube.png
  custom.css: |
    div#information-widgets {
      font-size: medium;
      font-family: monospace;
      font-weight: 800;
    }

    div.service-name{
      font-size: medium;
      font-weight: 800;
    }

    p.service-description {
      font-size: medium;
      font-family: monospace;
      font-weight: 800;
    }

    div.bookmark-name {
      font-size: medium;
    }

    div.bookmark-description {
      font-size: medium;
      font-weight: 800;
      font-family: monospace;
    }

    div.service-block div {
      font-size: medium;
      font-family: monospace;
      font-weight: 400;
    }

    li.service {
      border-radius: 4px;
    }

    div button h2 {
      font-weight: 800;
    }
  custom.js: ""
  docker.yaml: ""
  proxmox.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Cluster Management:
        - Tools:
          - Headlamp:
              href: "http://uno.lab.local:30677"
              description: "uno.lab.local:30677"
              icon: buddy.png
          - Longhorn:
              href: "http://uno.lab.local:31044"
              description: "uno.lab.local:31044"
              icon: longhorn.png
          - Kubevirt:
              href: "http://uno.lab.local:30867"
              description: "uno.lab.local:30867"
              icon: duo.png
          - Trilio:
              href: "http://duo.lab.local:30215/"
              description: "duo.lab.local:30215"
              icon: cup.png
    - Infrastructure:
        - Bare Metal:
            - Master-01:
                href: ""
                description: "hostname: uno [192.168.0.137]"
                icon: atuin.png
            - Master-02:
                href: ""
                description: "hostname: duo [192.168.0.101]"
                icon: atuin.png
        - Networking:
            - Router:
                href: http://dlinkrouter.local/admin/index.html#/home
                description: dlinkrouter.local
                icon: router.png
        - DNS:
            - Pihole-01:
                href: http://dns.lab.local/admin/
                description: dns.lab.local
                icon: pi-hole.png
    - Services:
        - Home Media:
          - Immich:
              href: http://immich.lab.local
              description: immich.lab.local
              icon: immich.png
              namespace: immich
              app: server
          - Jellyfin:
              href: http://uno.lab.local:32033/
              description: uno.lab.local:32033
              icon: jellyfin.png
        - Internet:
          - Firefox:
              href: https://uno.lab.local:30285/
              description: uno.lab.local:30285
              icon: firefox.png
          - Qbittorrent:
              href: http://uno.lab.local:30568/
              description: uno.lab.local:30568
              icon: qbittorrent.png
        - Development:
          - Codeserver:
              href: http://dev.lab.local/?folder=/root
              description: dev.lab.local
              icon: code-server.png
    - Storage:
      - Browsers:
          - File Browser:
              href: http://uno.lab.local:31949
              description: uno.lab.local:31949
              icon: filebrowser.png
          - Filezilla:
              href: http://uno.lab.local:8086/
              description: uno.lab.local:8086
              icon: filezilla.png
      - Data Transfer:
          # - FTP Server:
          #     href:
          #     description: "Host: uno.lab.local, Port: 8084/8085"
          #     icon: webkit.png
          - NFS Server:
              href:
              description: "Host: uno.lab.local, Share: /mnt"
              icon: webkit.png
  settings.yaml: |
    title: Aryan's Homepage
    cardBlur: none
    headerStyle: clean
    disableCollapse: true
    disableAutodiscovery: true
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
          expanded: true
    # - resources:
    #     show: false
    #     backend: resources
    #     expanded: false
    #     cpu: true
    #     memory: true
    #     network: default
    #     disk: /
