# Webcord - Discord client in browser
# https://github.com/SpacingBat3/WebCord
#
# Port: 8083 -> 3000 (Web UI)
# Default credentials: admin / admin

services:
  webcord:
    image: lscr.io/linuxserver/webcord:latest
    container_name: webcord
    hostname: webcord
    ports:
      - 8083:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - KEEP_APP_RUNNING=1
      - CUSTOM_USER=admin
      - PASSWORD=admin
      - TITLE=webcord
      - NO_DECOR=true
    volumes:
      - /ctnr/data:/config
    shm_size: 1gb
    restart: always
