# Heimdall - Application dashboard
# https://github.com/linuxserver/Heimdall
#
# Ports: 80, 443, 8080 -> 80

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    ports:
      - 80:80
      - 443:443
      - 8080:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /root/container/Stacks/heimdall/data:/config
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true
