# Traefik - Cloud-native reverse proxy and load balancer
# https://traefik.io/
#
# Ports: 80 (HTTP), 443 (HTTPS), 8080 (Dashboard)
# Configured for Podman socket

services:
  traefik:
    image: docker.io/traefik:v3.1
    container_name: traefik
    hostname: traefik
    user: root
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/podman/podman.sock:/var/run/docker.sock
      - /root/container/traefik/config:/etc/traefik
      - /root/logs:/root/logs
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true
