http:
  routers:
    TraefikApi:
      rule: "Host(`trfk.home.lab`) && PathPrefix(`/api/`)"
      service: api@internal
    TraefikDashboard:
      rule: "Host(`trfk.home.lab`)"
      service: dashboard@internal
    Portainer:
      rule: "Host(`ptnr.home.lab`)"
      service: portainer
    PortainerHttps:
      rule: "Host(`ptnr.home.lab`)"
      service: portainer
      tls: {}
      middlewares:
        - redirect-to-http
    Filebrowser:
      rule: "Host(`file.home.lab`)"
      service: filebrowser
    Qbittorrent:
      rule: "Host(`qbit.home.lab`)"
      service: qbittorrent
    Jellyfin:
      rule: "Host(`jelly.home.lab`)"
      service: jellyfin
    Pyload:
      rule: "Host(`pyload.home.lab`)"
      service: pyload
    Filezilla:
      rule: "Host(`filezilla.home.lab`)"
      service: filezilla
    Nextcloud:
      rule: "Host(`cloud.home.lab`)"
      service: nextcloud
    Pihole:
      rule: "Host(`pi.home.lab`)"
      service: pihole
    Cockpit:
      rule: "Host(`ckpt.home.lab`)"
      service: cockpit

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    filebrowser:
      loadBalancer:
        servers:
          - url: "http://filebrowser:80"
    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://qbittorrent:8083"
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://jellyfin:8096"
    pyload:
      loadBalancer:
        servers:
          - url: "http://pyload-ng:8000"
    filezilla:
      loadBalancer:
        servers:
          - url: "http://filezilla:5800"

    # Pihole and Nextcloud are deployed in separate Alpine Linux VM.
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://vm1.home.lab"
    pihole:
      loadBalancer:
        servers:
          - url: "http://vm1.home.lab:8080"

    # Cockpit is central management dashboard for machines.
    cockpit:
      loadBalancer:
        servers:
          - url: "http://host.home.lab:9090"

  middlewares:
    redirect-to-http:
      redirectScheme:
        scheme: "http"
