version: "3.8"
services:
  filezilla:
    image: jlesage/filezilla
    container_name: filezilla
    hostname: filezilla
    environment:
      - WEB_AUTHENTICATION_USERNAME=admin
      - WEB_AUTHENTICATION_PASSWORD=admin
      - WEB_AUTHENTICATION=1
      - WEB_AUDIO=1
      - SECURE_CONNECTION=1
      - KEEP_APP_RUNNING=1
      - TZ=Asia/Kolkata
    ports:
      - 8086:5800
    volumes:
      - /mnt/drive/filezilla:/config:rw
      - /mnt/drive:/storage:rw
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true
